<!-- Bibliotecas Javascript Padrão do ADMIN - NÂO ALTERAR -->
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/jquery/dist/jquery.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/tether/dist/js/tether.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/flot/jquery.flot.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/flot/jquery.flot.resize.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/flot.curvedlines/curvedLines.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/jquery.sparkline/jquery.sparkline.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/jquery.easy-pie-chart/dist/jquery.easypiechart.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/moment/min/moment.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/fullcalendar/dist/fullcalendar.min.js "></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/simpleWeather/jquery.simpleWeather.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/Waves/dist/waves.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bootstrap-growl/bootstrap-growl.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/sweetalert2/dist/sweetalert2.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/jquery.scrollbar/jquery.scrollbar.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/jquery-scrollLock/jquery-scrollLock.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/salvattore/dist/salvattore.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/datatables.net/js/jquery.dataTables.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/datatables.net-buttons/js/buttons.print.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/jszip/dist/jszip.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/flatpickr/dist/flatpickr.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/flatpickr/dist/l10n/pt.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/bootstrap-select/dist/js/bootstrap-select.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/typeahead.js/dist/typeahead.bundle.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/chosen/chosen.jquery.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/lightgallery/lib/lightgallery-all.min.js"></script>
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/fancybox/jquery.fancybox.min.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/highcharts.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/modules/exporting.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/fileinput/fileinput.min.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/bower_components/flot/jquery.flot.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/bower_components/flot/jquery.flot.pie.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/bower_components/flot/jquery.flot.resize.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/bower_components/flot/jquery.flot.categories.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/bower_components/flot.curvedlines/curvedLines.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/bower_components/flot.orderbars/js/jquery.flot.orderBars.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/summernote/dist/summernote.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/summernote/dist/lang/summernote-pt-BR.js"></script>
<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/vendors/bower_components/jquery-sortable-photos/jquery-sortable-photos.js"></script>


<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/app.min.js"></script>

<!-- Fim das bibliotecas Javascript do ADMIN -->

<!-- Adicionar bibliotecas adicionais abaixo -->
<!-- MINHA FUNÇÃO JS -->
<script src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/funcoes.js"></script>

<script src="<?= BASE_SITE ?>vendor/CRO/BaseAdmin/js/jquery.nestable.js"></script>



<!-- Fim das bibliotecas adicionais -->

