  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/css/froala_editor.css">
  <link rel="stylesheet" href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/css/froala_style.css">
  <link rel="stylesheet" href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/css/plugins/code_view.css">
  <link rel="stylesheet" href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/css/plugins/image_manager.css">
  <link rel="stylesheet" href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/css/plugins/image.css">
  <link rel="stylesheet" href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/css/plugins/table.css">
  <link rel="stylesheet" href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/css/plugins/video.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.css">

  <!--
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/mode/xml/xml.min.js"></script>
  -->
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/froala_editor.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/align.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/code_beautifier.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/code_view.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/draggable.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/image.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/image_manager.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/link.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/lists.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/paragraph_format.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/paragraph_style.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/table.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/video.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/url.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/plugins/entities.min.js"></script>
  <script type="text/javascript" src="<?=BASE_SITE?>vendor/CRO/BaseAdmin/js/novo_editor/pt_br.js"></script>
