<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Painel Administrativo - <?=NOME_CLIENTE?></title>

	<!-- Vendor CSS -->
	<link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/fullcalendar/dist/fullcalendar.min.css" rel="stylesheet">
	<link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/animate.css/animate.min.css" rel="stylesheet">
	<link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet">
	<link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css" rel="stylesheet">
	<link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/jquery.scrollbar/jquery.scrollbar.css" rel="stylesheet">

    <link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/flatpickr/dist/flatpickr.min.css" rel="stylesheet">
    <link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/bootstrap-select/dist/css/bootstrap-select.css" rel="stylesheet">
    <link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/chosen/chosen.css" rel="stylesheet">
    <link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/lightgallery/dist/css/lightgallery.min.css" rel="stylesheet">
    <link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/bower_components/fancybox/jquery.fancybox.min.css" rel="stylesheet">
    <link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/vendors/summernote/dist/summernote.css" rel="stylesheet">

    <!-- FAVICON -->
    <link rel="apple-touch-icon" sizes="57x57" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/favicon-16x16.png">
    <link rel="manifest" href="<?=BASE_SITE?>App/Views/includes/imagens/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<?=BASE_SITE?>App/Views/includes/imagens/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

	<!-- CSS -->
	<link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/css/app.min.css" rel="stylesheet">

    <!-- MINHA FOLHA DE ESTILOS -->
    <link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/css/estilos.css" rel="stylesheet">
    <link href="<?=BASE_SITE?>vendor/CRO/BaseAdmin/css/nestable.css" rel="stylesheet">


</head>