<!DOCTYPE html>
<html lang="pt-BR">
    <?php include_once('includes/head.phtml');?>
    <body data-ma-theme="meuTema">
        <main class="main">
            <div class="page-loader">
                <div class="page-loader__spinner">
                    <svg viewBox="25 25 50 50">
                        <circle cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
                    </svg>
                </div>
            </div>

            <?php include_once('includes/menu_topo.phtml');?>
            <?php include_once('includes/chamadas_javascript.phtml');?>
            <?php include_once('includes/menu_lateral.phtml');?>
            <?php // include('chat.phtml'); //verificar o uso e a necessidade?>

            <section class="content">
                <?php if(@$this->view->header):?>
                    <header class="content__title">
                        <h1><?=$this->view->header?></h1>
                        <?=@$this->view->headerSmall ? "<small>" . $this->view->headerSmall . "</small>" : ""?>
                    </header>
                    <?php
                endif;
                /***** Todo o conteúdo do site vai entrar aqui *****/
                echo $this->content();?>
                <?php include_once('includes/footer.phtml');?>
            </section>
        </main>
    </body>
</html>